/* Themed "Most likely to..." packs. Written for adults — chaotic, not cruel. */
(function (global) {
  var PACKS = [
    {
      id: 'classic', name: 'Classic', emoji: '🎲', accent: '#ffd23f', title: 'Household Name',
      items: [
        "become a millionaire",
        "get lost in their own neighbourhood",
        "cry at a movie nobody else cried at",
        "text back three days later",
        "become famous for something ridiculous",
        "adopt seven cats",
        "start a podcast nobody asked for",
        "forget their own birthday",
        "win an argument they were clearly losing",
        "get a tattoo on impulse",
        "move to another country on a whim",
        "be late to their own wedding",
        "fall asleep at a party",
        "know every word to a musical",
        "accidentally join a cult",
        "talk their way out of a speeding ticket",
        "run a marathon with zero training",
        "lose their phone twice in one night",
        "have a secret second life",
        "give the best advice at 2am",
        "become everyone's unpaid therapist",
        "get away with the perfect prank",
        "still be gaming at 60",
        "show up with snacks for everyone",
        "laugh at the worst possible moment",
        "be the first to say 'I told you so'",
        "sing karaoke completely sober",
        "have the messiest room",
        "make friends with a stranger in five minutes",
        "be the designated driver forever",
        "take the best photos and never post them",
        "be the last one on the dance floor",
        "google their symptoms and start panicking",
        "read the message and never reply",
        "be a great parent one day",
        "be the reason we get kicked out",
        "become the group's official planner",
        "give a stranger their last twenty bucks",
        "forget where they parked every single time",
        "win a raffle they don't remember entering",
        "have a signature dance move nobody asked for",
        "be the human alarm clock of the group",
        "start every diet on a Monday and quit by Wednesday"
      ]
    },
    {
      id: 'night', name: 'Night Out', emoji: '🍻', accent: '#ff2d95', title: 'Public Liability',
      items: [
        "black out and wake up in a different city",
        "lose one shoe and not notice until morning",
        "start a conga line at a funeral reception",
        "text their ex at 3am and blame autocorrect",
        "try to fight a bouncer twice their size",
        "buy a $400 round they absolutely cannot afford",
        "fall asleep in the cab and end up at the depot",
        "get on stage completely uninvited",
        "swear they're fine while holding a wall for support",
        "adopt four strangers as their new best friends",
        "drop their phone in a toilet and go back in for it",
        "insist on one more bar at 4am",
        "wake up with a traffic cone they cannot explain",
        "start every night saying 'just one drink'",
        "end up in the DJ booth",
        "cry about their childhood pet to a stranger",
        "do the karaoke song that clears the room",
        "buy a kebab and lose it before eating it",
        "be the reason there's a group apology text the next day",
        "eat something deeply questionable from a street cart",
        "try to walk 14 km home instead of getting a cab",
        "convince everyone to go swimming fully clothed",
        "come back from the bathroom with a new tattoo idea",
        "still be going when the sun comes up",
        "start a round of shots nobody agreed to",
        "lose an entire hour and have no memory of it",
        "order a round of tequila shots for strangers",
        "end up on someone's shoulders by midnight",
        "lose their coat and never see it again",
        "become best friends with the bartender in one night",
        "start crying happy tears over a slow song",
        "try to pay with the wrong currency",
        "convince the bouncer they're on the list",
        "end up barefoot before the night is over",
        "start a debate about pineapple on pizza at 2am",
        "get separated from the group and reappear an hour later with a new friend",
        "order food for the whole table and forget to eat any",
        "become the unofficial photographer of everyone's worst angles",
        "fall for the 'one more round' trap every single time",
        "end the night doing karaoke solo to an empty room",
        "leave their card behind at three different bars",
        "wake up still wearing sunglasses"
      ]
    },
    {
      id: 'crime', name: 'Petty Crime', emoji: '🚔', accent: '#ff5c39', title: 'Most Wanted',
      items: [
        "get arrested for something incredibly stupid",
        "plan the perfect heist and get caught bragging about it",
        "go to jail and come out with a business idea",
        "steal a road sign for their bedroom wall",
        "get caught shoplifting something worth two dollars",
        "accidentally get into the wrong car and just go with it",
        "run a suspiciously profitable scheme on their own family",
        "get banned from an entire country",
        "be an unbelievably bad witness in court",
        "confess to a crime nobody accused them of",
        "keep stolen hotel towels for twenty years",
        "get pulled over and offer the officer a snack",
        "forge a doctor's note as a grown adult",
        "turn up on the news in the background of a raid",
        "start an underground poker night that gets shut down",
        "sell something extremely fake online and get away with it",
        "get a record for a protest they wandered into by accident",
        "argue with a parking ticket for eleven months",
        "sneak into a festival and end up backstage",
        "borrow something permanently and call it a loan",
        "be the getaway driver who stops at a yellow light",
        "get away with everything purely on charm",
        "jaywalk directly in front of a police officer",
        "return something to a store well after using it",
        "claim a fake food allergy to skip the line",
        "sneak snacks into a movie theater like a professional",
        "talk their way out of a library fine",
        "get a warning for something they clearly did on purpose",
        "take the 'one free sample' rule way too literally",
        "reverse a parking ticket through sheer charm",
        "be the mastermind of an office supply heist",
        "forge a permission slip as an adult for no reason",
        "cut in line and somehow make it look like an accident",
        "get caught regifting something to the person who gave it",
        "run a black market for parking spots",
        "'borrow' a shopping cart permanently",
        "convince a group chat to cover up something minor",
        "be suspiciously good at picking locks",
        "know a guy for absolutely everything",
        "get pulled over for a taillight and leave with a compliment",
        "smuggle snacks anywhere food isn't allowed",
        "walk out of a store still holding a fitting-room item by accident on purpose"
      ]
    },
    {
      id: 'apocalypse', name: 'Apocalypse', emoji: '☢️', accent: '#b6ff3b', title: 'Last One Standing',
      items: [
        "survive the apocalypse purely by luck",
        "be the first to go in a horror movie",
        "become a warlord of the wasteland",
        "trade the group's last food for something useless",
        "build a bunker and forget the door code",
        "be immune to the virus and insufferable about it",
        "start a cult in the ruins of a shopping mall",
        "die trying to save a cat",
        "sell us out for one can of peaches",
        "become the leader nobody voted for",
        "survive on vibes alone",
        "give their crossbow a name",
        "be the reason the horde finds us",
        "refuse to leave their apartment and somehow be fine",
        "ride a horse into a gas station",
        "reinvent the wheel incorrectly",
        "crown themselves emperor of the parking lot",
        "keep posting through the end of the world",
        "volunteer for the suicide mission and thrive",
        "eat the mystery mushroom",
        "start bartering in trading cards",
        "hoard something completely worthless",
        "make it to year two and get bored of it",
        "turn a shopping mall into a fortified kingdom",
        "be the one who insists on going back for the dog",
        "barter with the wrong group and regret it",
        "become disturbingly good at using a bow and arrow overnight",
        "keep morale high with terrible jokes",
        "name every zombie they encounter",
        "find the one working vending machine in the wasteland",
        "start a garden nobody asked for",
        "be voted off the survivor council first",
        "turn out to have been the traitor all along",
        "stockpile something nobody else thinks is useful",
        "accidentally lead the horde straight to camp",
        "become fluent in Morse code just in case",
        "build a trap that only catches teammates",
        "be the reason the generator finally works",
        "insist the apocalypse is 'actually kind of nice'",
        "keep a diary nobody will ever read",
        "become the camp's reluctant doctor with zero training",
        "survive by pure main-character energy"
      ]
    },
    {
      id: 'money', name: 'Rich & Ruined', emoji: '💸', accent: '#3dff9e', title: 'Financially Feral',
      items: [
        "lose everything on a single bet",
        "become a millionaire and immediately buy something insane",
        "get rich off a coin they bought as a joke",
        "go bankrupt buying a jet ski",
        "fall for a pyramid scheme and try to recruit us",
        "spend an entire paycheque within one hour",
        "own six cars and no couch",
        "become a landlord and get weird about it",
        "win the lottery and tell literally everyone",
        "retire at 35 and be bored by 36",
        "day-trade their rent money",
        "get sponsored by an energy drink",
        "become a crypto guy at someone's wedding",
        "have a nine-dollar coffee habit and complain about rent",
        "buy a house sight-unseen in a country they can't spell",
        "get scammed and then defend the scammer",
        "open a restaurant with zero cooking experience",
        "keep a secret fortune under a mattress",
        "become a millionaire's suspicious new best friend",
        "sell their car to fund an idea nobody understood",
        "expense something outrageous and get away with it",
        "be rich and still split the bill down to the cent",
        "invest in something because the branding was nice",
        "forget they own stock in something huge",
        "never once check their bank balance",
        "tip a stranger's entire bill for no reason",
        "start a business plan on a napkin that actually works",
        "lease a car they absolutely cannot afford",
        "win big and immediately lose it at the same table",
        "become the friend who always 'forgets' their wallet",
        "turn a garage sale into a small empire",
        "buy the extended warranty on literally everything",
        "finally pay off debt and celebrate by creating more",
        "become suspiciously calm about an audit",
        "flip a house and somehow lose money doing it",
        "treat a bonus like it's already spent",
        "start a group investment that ends in silence",
        "never split a bill correctly",
        "quietly become rich and never mention it",
        "go through a phase of only paying in cash 'for privacy'",
        "buy a boat with zero boating experience",
        "donate a suspicious amount to a cause nobody's heard of"
      ]
    },
    {
      id: 'online', name: 'Extremely Online', emoji: '📱', accent: '#22e6ff', title: 'Terminally Online',
      items: [
        "go viral for the worst possible reason",
        "get cancelled over something they posted in 2013",
        "start a podcast and make us all listen to it",
        "become an influencer in a niche nobody knew existed",
        "reply to a celebrity until they get blocked",
        "livestream something they absolutely should not",
        "have a secret account with four thousand followers",
        "fall in love with a chatbot",
        "get catfished and stay in it out of politeness",
        "read one article and become an expert",
        "argue with strangers about pizza for six hours",
        "post a story that was meant for exactly one person",
        "become a meme",
        "leave an unhinged public review of a sandwich shop",
        "start a beef with a local bakery",
        "fake an entire vacation with stock photos",
        "get community-noted",
        "run a fan account for something embarrassing",
        "doxx themselves by accident",
        "get famous online and pretend to hate it",
        "leave one star over a napkin",
        "turn their whole personality into a niche subreddit",
        "livetweet a stranger's argument on a train",
        "screenshot a private chat and forget who they sent it to",
        "have a burner account older than their real one",
        "comment 'first' unironically",
        "get exposed by their own group chat history",
        "turn a typo into a whole persona",
        "argue with a bot and lose",
        "become weirdly attached to a stranger's dog account",
        "post the same photo from twelve angles",
        "get recognized in public from a single viral post",
        "have their location guessed from a background object",
        "start beef with an app's customer support account",
        "screen-record something they shouldn't",
        "reply to their own post pretending to be someone else",
        "get quote-tweeted into oblivion",
        "turn off comments after one bad take",
        "have a 'finsta' more popular than their main",
        "unknowingly become a meme template",
        "get roasted in the replies and thank everyone individually",
        "have an ex like a post from three years ago"
      ]
    },
    {
      id: 'love', name: 'Love & Disaster', emoji: '💔', accent: '#ff5cad', title: 'Romantically Doomed',
      items: [
        "get married in Vegas on a Tuesday",
        "date someone purely to annoy their family",
        "propose embarrassingly early",
        "ghost someone and run into them the next day",
        "have a wedding with a dress code nobody agreed to",
        "fall in love on a first date and announce it in the group chat",
        "get back with an ex for the fifth time",
        "bring a first date to a family funeral",
        "write a love letter they instantly regret",
        "have a breakup playlist ready to go at all times",
        "get engaged after a two-week holiday romance",
        "keep a spreadsheet of dating prospects",
        "be the reason a friend group splits in half",
        "have a very public argument in a restaurant",
        "move in together after three weeks",
        "have a 'type' and refuse to admit it",
        "send a paragraph when a text would do",
        "get a tattoo of a partner's name",
        "be a serial monogamist and deny it",
        "do the grand romantic gesture at an airport",
        "date someone we all warned them about",
        "still be friends with every single ex",
        "fall for someone purely because of their playlist",
        "plan a whole future around a first date",
        "forget an anniversary and blame the calendar app",
        "date two people with the exact same name and confuse them",
        "get relationship advice from the worst possible person",
        "write vows that make the officiant cry laughing",
        "send a risky text and immediately request to unsend it",
        "fall in love with someone's dog before the person",
        "have a situationship longer than most marriages",
        "introduce a partner to the family way too soon",
        "break up over something neither of them remembers",
        "stay friends with an ex's whole family",
        "plan an elaborate proposal that goes hilariously wrong",
        "fall for the 'we're just talking' trap every time",
        "have a wedding hashtag nobody can spell",
        "date someone purely for their cooking",
        "cry happy tears at literally every wedding",
        "be the reluctant maid of honor who steals the show",
        "get matched with a friend's ex on an app",
        "plan the honeymoon before the actual wedding"
      ]
    },
    {
      id: 'work', name: 'Work Meltdown', emoji: '💼', accent: '#9d6bff', title: "HR's Problem",
      items: [
        "quit dramatically over something tiny",
        "reply-all to four thousand people",
        "get promoted for doing absolutely nothing",
        "try to unionise a smoothie shop",
        "fall asleep in a meeting with their camera on",
        "lie on their résumé and get the job anyway",
        "get caught working two full-time jobs",
        "insult the CEO in the wrong chat window",
        "turn a side hustle into an actual empire",
        "take a three-hour lunch and act offended about it",
        "microwave fish in the office kitchen",
        "automate their entire job and tell nobody",
        "cry in a bathroom over a spreadsheet",
        "become middle management and change as a person",
        "have a LinkedIn post go horribly wrong",
        "get fired and not mention it for a month",
        "name their startup something unforgivable",
        "be the entire office gossip network",
        "speak the most in a meeting that could have been an email",
        "put 'visionary' in their job title",
        "cause an incident on a work trip",
        "hand in a resignation letter as a poem",
        "schedule a meeting that could've been a two-word email",
        "get promoted by accident",
        "have a nemesis in a completely unrelated department",
        "bring homemade snacks to guilt the office into liking them",
        "become the unofficial IT support for the whole floor",
        "forget to mute during something embarrassing",
        "turn a five-minute task into a whole committee",
        "know way too much office gossip for someone so new",
        "negotiate a raise using a meme deck",
        "get stuck training their own replacement",
        "accidentally CC the wrong person on something spicy",
        "pitch an idea that gets stolen by their boss",
        "be the reason the office plant died",
        "start a betting pool on company drama",
        "survive three rounds of layoffs through sheer luck",
        "give a TED-talk-energy answer to a simple question",
        "become 'that' person who reply-alls with a GIF",
        "take a sick day to attend a concert and get spotted",
        "invent a job title that means nothing",
        "quietly run the entire department from an unofficial role"
      ]
    },
    {
      id: 'unhinged', name: 'Deeply Unhinged', emoji: '🤪', accent: '#ff7ae0', title: 'Certified Unhinged',
      items: [
        "start a cult by accident and be surprised it worked",
        "keep a raccoon as an emotional support animal",
        "get in a physical fight with a goose and lose",
        "eat something off the floor of a train station",
        "claim they were abducted and have a slideshow ready",
        "name their child after a video game character",
        "be found living inside an IKEA",
        "have a favourite tooth",
        "talk to a plant and get an answer",
        "microwave metal just to see what happens",
        "own a sword for no reason at all",
        "lick something in a museum",
        "genuinely believe they could beat a bear in a fight",
        "get a face tattoo on a whim",
        "be legally required to stay away from a zoo",
        "collect something deeply concerning",
        "move to the woods and go completely feral",
        "pick up an accent and never drop it",
        "keep a jar of teeth",
        "get barred from a Denny's",
        "run for office on one insane policy",
        "buy a coffin before they need it",
        "have a five-year plan involving a swamp",
        "have strong opinions about cereal physics",
        "befriend a bird that clearly hates them",
        "keep a to-do list from three years ago just in case",
        "talk in a fake accent until it becomes permanent",
        "have a favorite parking spot they'll fight for",
        "collect receipts for no discernible reason",
        "believe they have a sixth sense for parking",
        "name inanimate objects and mourn them when they break",
        "have an elaborate theory about a completely mundane topic",
        "be weirdly competitive about board games with children",
        "keep every fortune cookie slip ever received",
        "have an entire personality built around one TV show",
        "insist on doing everything 'the hard way' out of principle",
        "argue with a GPS out loud",
        "be suspicious of all birds specifically",
        "start a feud with a vending machine",
        "own exactly one too many novelty mugs",
        "have a secret talent that makes no sense",
        "be convinced they'd thrive in a completely different century"
      ]
    },
    {
      id: 'travel', name: 'Travel Chaos', emoji: '✈️', accent: '#4ad9ff', title: 'Flight Risk',
      items: [
        "miss a flight while sitting at the gate",
        "get detained at a border over a joke",
        "lose their passport twice on one trip",
        "book the wrong city and go anyway",
        "get on the wrong train and just commit to it",
        "ride a scooter with no licence and no helmet",
        "eat the street food that ends the trip",
        "do two weeks out of a bag the size of a loaf of bread",
        "be the reason we get thrown off a boat",
        "pack nothing but sunglasses",
        "disappear for six hours and come back with a story",
        "befriend a local and never come home",
        "get sunburnt in a shape",
        "try to haggle in a fixed-price store",
        "pay three hundred dollars for a 'shortcut'",
        "climb something they should absolutely not climb",
        "get stuck in an airport for thirty hours and thrive",
        "lose the entire group in a market",
        "rent a car in a country that drives on the other side",
        "swim somewhere with a very clear warning sign",
        "come home with an animal",
        "book a hostel on price alone and regret everything",
        "bring back a souvenir nobody wants",
        "get hopelessly lost with full confidence",
        "try to fit a week's worth of plans into a layover",
        "become best friends with a stranger at baggage claim",
        "forget which country they're in for a second",
        "argue with airport security over a bottle of water",
        "pack a full itinerary and follow none of it",
        "end up the unofficial translator despite knowing zero words",
        "get stopped for a 'random' check every single time",
        "upgrade to business class through pure charm",
        "bring back a stray animal story from every trip",
        "nap through the one thing everyone wanted to see",
        "get talked into a timeshare presentation for the free breakfast",
        "turn a two-day trip into a full identity crisis",
        "be the reason the group misses a train",
        "negotiate a room upgrade at every hotel",
        "eat the same meal in every country they visit",
        "get a sunburn in the shape of their sunglasses",
        "collect passport stamps like a competitive sport",
        "become suspiciously good at every local dialect within a week"
      ]
    },
    {
      id: 'fitness', name: 'Fitness Fanatic', emoji: '🏋️', accent: '#ff4d4d', title: 'Gym Legend',
      items: [
        "post a gym selfie mid-set",
        "start a diet on Monday and abandon it by lunch",
        "own more workout gear than actual workouts completed",
        "talk about their 'macros' unprompted",
        "get injured stretching, not lifting",
        "convince the whole group to try a 5am workout class",
        "have a playlist that's 90% hype, 10% actual songs",
        "quit a marathon halfway and call it 'strategic pacing'",
        "become weirdly competitive at a casual group hike",
        "wear a fitness tracker to bed and brag about sleep scores",
        "argue about protein shakes like it's a religion",
        "take up a new sport and buy all the gear before learning the rules",
        "do a juice cleanse and complain the whole time",
        "have a gym nickname nobody else uses",
        "train for a 5k and somehow finish last",
        "become a yoga instructor after two classes",
        "cancel a gym membership they never used",
        "do one workout video and declare themselves 'basically a trainer'",
        "bring a protein bar to every single event",
        "get way too into a fitness app leaderboard",
        "challenge everyone to a plank contest uninvited",
        "buy a rowing machine that becomes a coat rack",
        "train an entire year for a race they forget to sign up for",
        "have strong opinions about the 'right' way to stretch",
        "go all in on a sport for exactly two weeks",
        "be suspiciously strong for someone who 'never works out'",
        "start every sentence with 'since I started lifting'",
        "do a triathlon on a dare",
        "be the loudest person at spin class",
        "buy running shoes more expensive than their rent",
        "convince the group to do a mud run 'for fun'",
        "get a personal trainer and immediately ignore all advice",
        "turn a walk to the mailbox into a 'cardio session'",
        "track every step like it's a competitive sport",
        "have a foam roller they've never actually used",
        "claim a hangover as 'active recovery'",
        "start CrossFit and never stop talking about it",
        "do a headstand at a party to prove a point",
        "get extremely serious about pickleball out of nowhere",
        "have a supplement cabinet bigger than the fridge",
        "insist on taking the stairs to prove a point",
        "wear compression socks unironically to brunch"
      ]
    },
    {
      id: 'pets', name: 'Pet Parent', emoji: '🐾', accent: '#8bc34a', title: 'Crazy Animal Person',
      items: [
        "talk to their pet like it's a full grown adult",
        "have more photos of their pet than their own family",
        "throw their dog a birthday party with a guest list",
        "get a pet DNA test purely for bragging rights",
        "dress their pet up for absolutely no occasion",
        "let the cat win every argument",
        "buy a couch and let the dog claim it within a day",
        "know their pet's opinions on specific houseguests",
        "have a pet with a more active social media than they do",
        "cry harder over a pet's vet visit than their own doctor's appointment",
        "adopt 'just one more' animal against everyone's advice",
        "train a pet to do one incredibly specific useless trick",
        "let a pet pick the new apartment",
        "have a pet who is banned from at least one relative's house",
        "narrate their pet's inner thoughts out loud",
        "buy pet furniture nicer than their own",
        "have a whole rotation of nicknames for one animal",
        "get a tattoo of their pet's face",
        "plan vacations entirely around pet-sitting logistics",
        "insist their pet is basically a genius",
        "have matching outfits with their dog",
        "bring a pet to a party uninvited and somehow it's fine",
        "start a small business because of their pet's personality",
        "get more excited for the pet's checkup than their own",
        "let a goldfish outlive several other plans",
        "have a pet that hates everyone but them",
        "be the reason the vet knows them by first name",
        "foster 'just one' litter and keep them all",
        "build furniture specifically for a cat that ignores it",
        "have full conversations about a pet's mood swings",
        "know their pet's exact opinion on the mailman",
        "buy pet insurance more comprehensive than their own health plan",
        "host a whole funeral for a childhood pet",
        "have a pet who's met more people than they have",
        "talk their landlord into an 'emotional support' anything",
        "be the unofficial neighborhood pet-sitter for free",
        "own a leash collection bigger than their shoe collection",
        "get a pet a matching bandana for every holiday",
        "have their pet's face as their phone background, lock screen, and wallpaper",
        "start crying at pet adoption videos every single time",
        "defend their pet's bad behavior like a lawyer",
        "let a pet interrupt every video call",
        "name a pet after a celebrity unironically"
      ]
    }
  ];

  function shuffle(a, rnd) {
    a = a.slice();
    rnd = rnd || Math.random;
    for (var i = a.length - 1; i > 0; i--) {
      var j = Math.floor(rnd() * (i + 1));
      var t = a[i]; a[i] = a[j]; a[j] = t;
    }
    return a;
  }

  /* Pseudo-packs for questions that came from the room rather than a pack. */
  var EXTRA = {
    room: { id: 'room', name: 'From the room', emoji: '🎤', accent: '#ffd23f', title: 'House Legend' },
    host: { id: 'host', name: 'House rules', emoji: '🏠', accent: '#ff8a3d', title: 'House Special' }
  };

  function packInfo(id) {
    for (var i = 0; i < PACKS.length; i++) if (PACKS[i].id === id) return PACKS[i];
    return EXTRA[id] || EXTRA.room;
  }

  global.MLT = global.MLT || {};
  global.MLT.PACKS = PACKS;
  global.MLT.packInfo = packInfo;
  global.MLT.shuffle = shuffle;
})(window);
